[build-system]
requires = [
           "setuptools>=42",
		   "wheel",
		   "numpy>=1.19.2",
		   "opencv-python>=4.5.1",
		   "pyautogui>=0.9.48",
		   "keyboard"
]
build-backend = "setuptools.build_meta"
